# read: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x run.sh
          ./run.sh

      - run: mkdir dist

      - name: Disable jekyll
        run: touch dist/.nojekyll

      - name: Copy files
        run: |
          cp -r lib dist
          cp -r out dist
          cp -r index.html dist

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx deploy-website gh dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
